language: go # specifies tools needed for building.

# Refer to https://docs.travis-ci.com/user/customizing-the-build/
script: # specifies the building procedure.
  # execute_templates.go reads ./template.txt and writes to ./executed_template.txt
  - go run execute_templates.go 

# Refer to https://docs.travis-ci.com/user/deployment/releases
deploy:
  provider: releases # deploy to Github Release objects. 
  api_key: "d303fcee75f90dfa5c74e81e7c84406061ed340c" # Github Oauth token
  file: $TRAVIS_BUILD_DIR/executed_template.txt
  skip_cleanup: true
  on:
    tags: true # Deploy only tags, not branches.
